name: Link2App Build
on:
  workflow_dispatch:
    inputs:
      url:
        required: true
        type: string
      app_name:
        required: true
        type: string
      version:
        required: true
        type: string
      targets:
        required: true
        type: string
      architecture:
        required: true
        type: string
      build_id:
        required: true
        type: string

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: macos-latest
            targets: dmg,app
          - os: ubuntu-latest
            targets: deb,appimage
    runs-on: ${{ matrix.os }}
    steps:
      - name: Build
        run: echo "Building ${{ github.event.inputs.targets }}"
